//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fix
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int ProfessionalID { get; set; }
        public int ProductID { get; set; }
        public string ProblemDetails { get; set; }
        public string FixDetails { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PaymentConfirmation { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Professional Professional { get; set; }
        public virtual Product Product { get; set; }
    }
}
