//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professional()
        {
            this.Fixes = new HashSet<Fix>();
        }
    
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public Nullable<bool> IsExpert { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Specialty { get; set; }
        public string VisitsArea { get; set; }
        public Nullable<decimal> VisitPrice { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fix> Fixes { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
